#!/bin/bash
set -e

LABOARD_VERSION=1.0.2

INSTALL_DIR="/home/laboard/laboard"

# rebuild apt cache
apt-get update

# install build dependencies
apt-get install -y gcc g++ libc6-dev

# create user
adduser --disabled-login --gecos 'Laboard' laboard
chown -R laboard:laboard /home/laboard

# disable bower analytics for automated install
sudo -u laboard -H cat > /home/laboard/.bowerrc <<EOF
{
 "analytics": false
}
EOF

ln -sf /usr/bin/nodejs /usr/bin/node

# download and install laboard
mkdir -p ${INSTALL_DIR}
wget -nv "https://github.com/jubianchi/laboard/archive/${LABOARD_VERSION}.tar.gz" -O - | \
  tar -zvxf - --strip=1 -C ${INSTALL_DIR}
chown -R laboard:laboard ${INSTALL_DIR}

# copy default configs
cd ${INSTALL_DIR}/config
sudo -u laboard -H cp client.js-dist client.js
sudo -u laboard -H cp server.json-dist server.json

# setup server
cd ${INSTALL_DIR}/server
sudo -u laboard -H npm install

# setup client
cd ${INSTALL_DIR}/client
sudo -u laboard -H npm install
sudo -u laboard -H bower install
sudo -u laboard -H node_modules/gulp/bin/gulp.js app

# allow the laboard user to bind port 80 via authbind
touch /etc/authbind/byport/80
chown laboard:root /etc/authbind/byport/80
chmod 744 /etc/authbind/byport/80

# purge build dependency packages
apt-get purge -y --auto-remove gcc g++ libc6-dev

# clean up
rm -rf /var/lib/apt/lists/*
